### PR TITLE
DOC: Provide author email to allow package setup

### PR DESCRIPTION
**Pull request by jhlegarreta**
Provide author email to allow package setup.

Fixes:
```
warning: check: missing meta-data: if 'author' supplied, 'author_email' must be supplied too

running check
error: Please correct your package.
```

raised in
https://github.com/brainhackorg/brainmatch/runs/2723550238?check_suite_focus=true#step:9:10

### CODE REVIEW

**Review by anibalsolon — APPROVED** [review]
LGTM!

**Review by eurunuela — APPROVED** [review]
LGTM!

**Comment by jhlegarreta** [comment]
Thanks both !

**Comment by jhlegarreta** [comment]
Package tests are passing now :ok_hand:.

**Pull request merged**
